version: '3.4'
services:
   app:
      image: vonproteus/youtube-to-podcast
      build:
         context: ./
         dockerfile: Dockerfile
      environment:
         - YTURL=https://www.youtube.com/watch?v=dQw4w9WgXcQ
         - MINSLEAP=1
         - MAXSELEAP=5
         - LIMITRATE=999M
         - YTDLOPTIONS= --verbose --max-downloads 1
         - CPUID=504
         - YT_GIT_REVISION=d8f134a664d7be2c10aba44fc2d54a8f7b0542ff
      networks:
         - external
      volumes:
         - ./test/:/data/
#         - testVolume:/data/

networks:
   external:

volumes:
   testVolume:

### Environment variables
